config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]

  resources :directors
  resources :actors
  resources :movies do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_and_belongs_to_many :movies

  def to_s
    self.name
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  load_and_authorize_resource

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<%= simple_form_for(@actor, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<div class="container">
  <h1>Editing Actor</h1>

  <%= render 'form', actor: @actor %>

  <%= link_to 'Show', @actor, class: "btn btn-primary" %>
  <%= link_to 'Back', actors_path, class: "btn btn-secondary" %>
</div>

app/views/actors/index.html.erb
<div class="container">
  <h1>Actors</h1>

  <%= link_to 'New Actor', new_actor_path, class: "btn btn-primary" %>
  <br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Some movies</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @actors.each do |actor| %>
        <tr>
          <td><%= actor.name %></td>
          <td><%= actor.movies.sample(3).join ", " %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, actor, class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_actor_path(actor), class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, actor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/actors/new.html.erb
<div class="container">
  <h1>New Actor</h1>

  <%= render 'form', actor: @actor %>

  <%= link_to 'Back', actors_path, class: "btn btn-secondary" %>
</div>

app/views/actors/show.html.erb
<div class="container">
  <h2><%= @actor %>'s movies</h2>

  <%= render partial: "movies/movies", locals: {movies: @actor.movies} %>

  <%= link_to 'Edit', edit_actor_path(@actor), class: "btn btn-primary" %>
  <%= link_to 'Back', actors_path, class: "btn btn-secondary" %>
</div>