config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]

  resources :directors
  resources :actors
  resources :movies do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index'
end

app/models/director.rb
class Director < ApplicationRecord
  has_and_belongs_to_many :movies

  def to_s
    self.name
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  load_and_authorize_resource

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= simple_form_for(@director, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<div class="container">
  <h1>Editing Director</h1>

  <%= render 'form', director: @director %>

  <%= link_to 'Show', @director, class: "btn btn-primary" %>
  <%= link_to 'Back', directors_path, class: "btn btn-secondary" %>
</div>

app/views/directors/index.html.erb
<div class="container">

  <h1>Directors</h1>

  <%= link_to 'New director', new_director_path, class: "btn btn-primary" %>
  <br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Some movies</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @directors.each do |director| %>
        <tr>
          <td><%= director.name %></td>
          <td><%= director.movies.sample(3).join ", " %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, director, class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_director_path(director), class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, director, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/directors/new.html.erb
<div class="container">
  <h1>New Director</h1>

  <%= render 'form', director: @director %>

  <%= link_to 'Back', directors_path, class: "btn btn-secondary" %>
</div>

app/views/directors/show.html.erb
<div class="container">

  <h2><%= @director %>'s movies</h2>

  <%= render partial: "movies/movies", locals: {movies: @director.movies} %>

  <%= link_to 'Edit', edit_director_path(@director), class: "btn btn-primary" %>
  <%= link_to 'Back', directors_path, class: "btn btn-secondary" %>
</div>