config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]

  resources :directors
  resources :actors
  resources :movies do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index'
end

app/models/user.rb
class User < ApplicationRecord
  require 'digest/md5'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def gravatar
      md5 = Digest::MD5.hexdigest(self.email)
      "https://www.gravatar.com/avatar/#{md5}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  def edit
  end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)
  #
  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      u_params = user_params
      u_params[:password] = @user.password if u_params[:password] == ""
      if @user.update(u_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :admin %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">

  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path, class: "btn btn-secondary" %>

</div>

app/views/users/index.html.erb
<div class="container">

  <h1>Users</h1>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th></th>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.gravatar, height: "100px" %></td>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <div class="btn-group" role="group">
              <%= link_to '<i class="fa fa-eye"></i>'.html_safe, user, class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(user), class: "btn btn-small btn-secondary" %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/users/new.html.erb
<div class="container">

  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path, class: "btn btn-secondary" %>

</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-3">
      <figure class="figure">
        <img src="<%= @user.gravatar %>" class="figure-img img-fluid rounded" alt="<%= @user.name  %>">
      </figure>
    </div>
    <div class="col-md-9">

      <dl>
        <dt>Name</dt>
        <dd><%= @user.name %></dd>

        <dt>Email</dt>
        <dd><%= @user.email %></dd>

        <dt>Admin?</dt>
        <dd><%= @user.admin? ? "Yes" : "No" %></dd>

      </dl>

        <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %>
        <%= link_to 'Back', users_path, class: "btn btn-secondary" %>
    </div>
  </div>


</div>