config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]

  resources :directors
  resources :actors
  resources :movies do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'store#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/cbcb5949ff.js"></script>
  </head>

  <body>
    <div class="collapse bg-inverse" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 py-4">
            <h4 class="text-white">Sobre a Movie Store</h4>
            <p class="text-muted">Nós insistimos em vender filmes.</p>
          </div>
          <div class="col-sm-4 py-4">
            <h4 class="text-white">Opções</h4>
            <ul class="list-unstyled">
              <% if can? :manage, Movie %>
                <li><%= link_to "Movies", movies_path %></li>
              <% end %>
              <% if can? :manage, Actor %>
                <li><%= link_to "Actors", actors_path %></li>
              <% end %>
              <% if can? :manage, Director %>
                <li><%= link_to "Directors", directors_path %></li>
              <% end %>
              <% if can? :manage, User %>
                <li><%= link_to "Users", users_path %></li>
              <% end %>
              <% if user_signed_in? %>
                <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
                <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-inverse bg-inverse">
      <div class="container d-flex justify-content-between">
        <%= link_to "Movie Store", root_path, class: "navbar-brand" %>
        <%= form_tag(search_movies_path, method: :get) do %>
          <%= text_field_tag :query, params[:query], placeholder: "Busque por títulos", class: "form-control" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <%= "#{current_user.name} (#{current_user.email})" if user_signed_in? %>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>

    <div class="container">
      <% unless notice.nil? %>
        <div class="alert alert-info"><%= notice %></div>
      <% end %>

      <% unless alert.nil? %>
        <div class="alert alert-warning"><%= alert %></div>
      <% end %>
    </div>

      <%= yield %>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Movie Store é uma aplicação exemplo utilizada durante o <a href="http://cursorails.kutzke.com.br">curso de Ruby on Rails</a></p>
      </div>
    </footer>
  </body>
</html>